mysql:
  host: localhost
  port: 3306
  database: bubblemine
  user: root
  password: ''
messages:
  prefix: '&f(&b!&f) '
  no_permission: 'У вас нет разрешения!'
  offline: 'Игрок оффлайн!'
  add_use: 'Использование: &b/addtag <player> <title>&f!'
  send_use: 'Использование: &b/sendtag <player>&f!'
  add_title: 'Вы успешно добавили тиутл &b<title>&f игроку &b<player>&f!'
  no_money: 'У вас не хватает жвачек. Купить жвачки можно в нашем онлайн-магазине&b bubblemine.net&r'
  enable: 'Вы успешно включили титул <title>&f!'
  disable: 'Вы успешно выключили титул <title>&f!'
  send_title: 'Вы успешно отправили запрос на создание титула игроку &b<player>&f!'
  title: '&b&lСмотри в чат!'
  select_msg: '&bВнимание! &fПри создании титула, ознакомьтесь с правилами нашего проекта, в нашем сообществе вк:&b vk.com/bubblemine_vk&r
  &fЕсли вы создадите титул с нарушениями правил сервера, вас могут &cзаблокировать&f. Создавайте титул без оскорблений, мата, рекламы и религиозных отношений!
  Для создания титула напишите его в чат без слеша &b"/"&f. Для изменения цвета используйте цветовые коды. &fДля изменения шрифта, используйте сайт:&b textgenerator.ru/font/'
  symbol: 'Вы используете запрещенные символы (&b\&f,&b/&f,&b-&f). Попробуйте сново!'
  confirm: 'Вы успешно создали свой личный титул <title>&f! Пиши &b/tags&f для установки!'
permissions:
  tag: 'entrytitle.tag'
  send: 'entrytitle.send'
  add: 'entrytitle.add'
settings:
  cost: 199
  load: '&fЗагрузка...'
  none: '&cНет'
  menu_title: '&0Титулы (<page>/<max>)'
  material_title: BOOK
  material_title_select: ENCHANTED_BOOK
  lore:
    - '&f'
    - '&f Статус: &cНе активен'
    - '&f Кликай &bПКМ&f/&bЛКМ&f, для включения!'
    - '&f'
  lore_select:
    - '&f'
    - '&f Статус: &aАктивен'
    - '&f Кликай &bПКМ&f/&bЛКМ&f, для выключения!'
    - '&F'