name: EntryTitle
main: ru.entryset.title.main.Main
version: 1.0
api-version: 1.13
author: EntrySet
depend: [PlaceholderAPI, PlayerPoints]
commands:
  tags:
    aliases: [tag, title, titel, titles, titels, suffix]
  sendtag:
  addtag: